# Generated by Django 5.0.6 on 2025-08-28 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0006_add_colors_and_shapes_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='image',
            field=models.URLField(blank=True, help_text='Image URL for lesson', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video',
            field=models.URLField(blank=True, help_text='Video URL (YouTube/embed) for lesson', null=True),
        ),
    ]
