# Generated by Django 5.0.6 on 2025-08-28 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0015_remove_lesson_image_blue_remove_lesson_image_red_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colorimage',
            name='video',
        ),
    ]
