# Generated by Django 5.0.6 on 2025-08-28 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0019_story_video_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='drawings/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('mark', models.CharField(blank=True, help_text="Teacher's mark (e.g. A+, Good, etc.)", max_length=20, null=True)),
                ('feedback', models.TextField(blank=True, help_text="Teacher's feedback or comments", null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawings', to='kids.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
