# Generated by Django 5.0.6 on 2025-08-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0020_drawing'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube or video embed URL for the lesson', null=True),
        ),
    ]
