# Generated by Django 5.0.6 on 2025-08-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0024_remove_lessoncompletion_activity_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncompletion',
            name='teacher_approved',
            field=models.BooleanField(default=False),
        ),
    ]
