# Generated by Django 5.0.6 on 2025-09-03 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0040_lesson_poster_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.ManyToManyField(blank=True, related_name='enrolled_users', to='kids.course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kids_userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
