# Generated by Django 5.0.6 on 2025-08-24 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('kid', 'Kid')], default='normal', max_length=10),
        ),
    ]
