# Generated by Django 5.0.6 on 2025-08-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('kid', 'Kid'), ('teacher', 'Teacher')], default='kid', max_length=10),
        ),
    ]
