# Generated by Django 5.0.6 on 2025-08-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0020_drawing'),
        ('users', '0003_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='courses',
            field=models.ManyToManyField(blank=True, help_text='Courses the student is enrolled in', related_name='students', to='kids.course'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('kid', 'Kid'), ('teacher', 'Teacher')], default='normal', max_length=10),
        ),
    ]
