from django.urls import path
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('snakes_ladders_player_select/', views.snakes_ladders_player_select, name='snakes-ladders-player-select'),
    path('snakes_ladders_mode/', views.snakes_ladders_mode, name='snakes-ladders-mode'),
    path('lesson/<int:lesson_id>/fill-blank-test/', views.fill_blank_test, name='fill_blank_test'),
    path('lesson/<int:lesson_id>/alphabet-quiz/', views.lesson_alphabet_quiz, name='lesson_alphabet_quiz'),
    path('alphabet-quiz/', views.alphabet_quiz, name='alphabet_quiz'),
    path('phonics-quiz/', views.phonics_quiz, name='phonics_quiz'),
    path('phonics-quiz-game/', views.phonics_quiz_game, name='phonics_quiz_game'),
    path('', views.home, name='kids_home'),
    path('funny-runner/', views.funny_runner, name='kids-funny-runner'),
    path('funny-runner-phaser/', views.funny_runner_phaser, name='kids-funny-runner-phaser'),
    path('space-shooter/', views.space_shooter, name='kids-space-shooter'),
    path('platformer_adventure/', views.platformer_adventure, name='kids-platformer-adventure'),
    path('arrow_throw/', views.arrow_throw, name='kids-arrow-throw'),
    path('puzzle_game/', views.puzzle_game, name='kids-puzzle-game'),
    path('brain_games/', views.brain_games, name='kids-brain-games'),
    path('digital_drawing/', views.digital_drawing, name='kids_drawing'),
    path('painting_game/', views.painting_game, name='kids_painting_game'),
    path('art_puzzle/', views.art_puzzle, name='kids_art_puzzle'),
    path('color-mixing-game/', views.color_mixing_game, name='color_mixing_game'),
    path('onlineplatform/', views.online_platform, name='kids_online_platform'),
    path('course/<int:course_id>/', views.course_detail, name='course_detail'),
    path('lesson/<int:lesson_id>/', views.lesson_detail, name='lesson_detail'),
    path('lesson/<int:lesson_id>/complete_quiz/', views.complete_alphabet_quiz, name='complete_alphabet_quiz'),
    path('lesson/<int:lesson_id>/complete_phonics_quiz/', views.complete_phonics_quiz, name='complete_phonics_quiz'),
    path('lesson/order/<int:order>/', views.lesson_by_order, name='lesson_by_order'),
    path('stories/', views.stories, name='kids_stories'),
    path('leaderboard/', views.leaderboard, name='kids_leaderboard'),
    path('play-screen/', views.play_screen, name='play_screen'),

    # Drawing upload and galleries
    path('lesson/<int:lesson_id>/upload_drawing/', views.upload_drawing, name='upload_drawing'),
    path('lesson/<int:lesson_id>/gallery/', views.drawing_gallery, name='drawing_gallery'),
    path('lesson/<int:lesson_id>/teacher_gallery/', views.teacher_drawing_gallery, name='teacher_drawing_gallery'),
    path('teacher/dashboard/', views.teacher_dashboard, name='teacher_dashboard'),
    path('performance/', views.performance, name='student_performance'),
    path('shape-matching-game/', views.shape_matching_game, name='shape_matching_game'),
    path('alphabet-lesson/', views.alphabet_lesson_detail, name='alphabet_lesson_detail'),
    path('level-select/', views.level_select, name='kids-level-select'),
    path('start-highscore/', views.start_highscore, name='kids-start-highscore'),
    path('lessons/alphabet/', views.alphabet_lesson_detail, name='alphabet_lesson_detail_alt'),
    path('lessons/simple-words-quiz/', views.simple_words_quiz_game, name='simple_words_quiz_game'),
    path('lessons/sight-words-quiz/', views.sight_words_quiz_game, name='sight_words_quiz_game'),
    path('lessons/blending-sounds/', views.blending_sounds_lesson, name='blending_sounds_lesson'),
    path('lessons/blending-quiz/', views.blending_sounds_quiz_game, name='blending_sounds_quiz_game'),
    path('entertainment/snakes-ladders/start/', views.snakes_ladders_start, name='snakes-ladders-start'),
    path('entertainment/snakes-ladders/', views.entertainment_snakes_ladders, name='entertainment-snakes-ladders'),
    path('virtual_pet/', views.virtual_pet, name='kids-virtual-pet'),
    path('snake_game/', views.snake_game, name='kids-snake-game'),
    path('api/courses/', views.course_list, name='course-list'),
    path('api/course/<int:course_id>/', views.course_detail_api, name='course_detail_api'),
    path('api/lesson/<int:lesson_id>/', views.lesson_detail_api, name='lesson_detail_api'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
