# Generated by Django 5.0.6 on 2025-08-28 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0010_create_quizquestion'),
        ('kids', '0010_merge_20250828_0802'),
    ]

    operations = [
    ]
