# Generated by Django 5.0.6 on 2025-08-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0012_alter_quizquestion_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image for the lesson', null=True, upload_to='lessons/'),
        ),
    ]
