# Generated by Django 5.0.6 on 2025-08-28 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0014_remove_lesson_image_lesson_image_blue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='image_blue',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='image_red',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='image_yellow',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video',
        ),
        migrations.CreateModel(
            name='ColorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('yellow', 'Yellow')], max_length=10)),
                ('image', models.ImageField(upload_to='lessons/colors/')),
                ('video', models.URLField(blank=True, help_text='Video URL (YouTube/embed) for lesson', null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_images', to='kids.lesson')),
            ],
        ),
    ]
