# Generated by Django 5.0.6 on 2025-08-30 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0025_lessoncompletion_teacher_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('color', 'Color'), ('shape', 'Shape'), ('animal', 'Animal'), ('number', 'Number')], max_length=20)),
                ('label', models.CharField(help_text='Name of the color, shape, animal, etc.', max_length=50)),
                ('image', models.ImageField(upload_to='lessons/images/')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_images', to='kids.lesson')),
            ],
        ),
    ]
