# Generated by Django 5.0.6 on 2025-08-31 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0030_remove_story_story_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('color', 'Color'), ('shape', 'Shape'), ('animal', 'Animal'), ('number', 'Number'), ('alphabet', 'Alphabet'), ('phonics', 'Phonics'), ('vowel', 'Vowel'), ('consonant', 'Consonant')], default='color', help_text='Type of lesson (color, shape, etc.)', max_length=20),
        ),
    ]
