# Generated by Django 5.0.6 on 2025-09-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0039_lessonposter'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='poster_image',
            field=models.ImageField(blank=True, help_text='Upload a poster for this lesson', null=True, upload_to='lesson_posters/'),
        ),
    ]
