# Generated by Django 5.0.6 on 2025-08-28 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0008_add_demo_media_lesson'),
        ('kids', '0009_force_demo_media_lesson'),
    ]

    operations = [
    ]
