# Generated by Django 5.0.6 on 2025-08-28 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0011_merge_20250828_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
