# Generated by Django 5.0.6 on 2025-08-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0016_remove_colorimage_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorimage',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('yellow', 'Yellow'), ('green', 'Green'), ('orange', 'Orange'), ('purple', 'Purple'), ('pink', 'Pink'), ('brown', 'Brown'), ('black', 'Black'), ('white', 'White')], max_length=10),
        ),
    ]
