# Generated by Django 5.0.6 on 2025-08-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0018_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube or video embed URL for the story', null=True),
        ),
    ]
