# Generated by Django 5.0.6 on 2025-08-30 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0023_lessoncompletion_activity_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessoncompletion',
            name='activity_approved',
        ),
        migrations.RemoveField(
            model_name='lessoncompletion',
            name='game_approved',
        ),
        migrations.RemoveField(
            model_name='lessoncompletion',
            name='learned_approved',
        ),
        migrations.RemoveField(
            model_name='lessoncompletion',
            name='quiz_approved',
        ),
        migrations.RemoveField(
            model_name='lessoncompletion',
            name='teacher_approved',
        ),
    ]
