# Generated by Django 5.0.6 on 2025-08-30 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0027_lesson_lesson_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='lesson',
            field=models.ForeignKey(blank=True, help_text='Link this story to a specific lesson', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='kids.lesson'),
        ),
    ]
