# Generated by Django 5.0.6 on 2025-08-28 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0013_alter_lesson_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='image',
        ),
        migrations.AddField(
            model_name='lesson',
            name='image_blue',
            field=models.ImageField(blank=True, help_text='Upload an image for Blue', null=True, upload_to='lessons/colors/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='image_red',
            field=models.ImageField(blank=True, help_text='Upload an image for Red', null=True, upload_to='lessons/colors/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='image_yellow',
            field=models.ImageField(blank=True, help_text='Upload an image for Yellow', null=True, upload_to='lessons/colors/'),
        ),
    ]
