# Generated by Django 5.0.6 on 2025-08-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0022_lessoncompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncompletion',
            name='activity_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lessoncompletion',
            name='game_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lessoncompletion',
            name='learned_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lessoncompletion',
            name='quiz_approved',
            field=models.BooleanField(default=False),
        ),
    ]
