# Generated by Django 5.0.6 on 2025-08-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0026_lessonimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('color', 'Color'), ('shape', 'Shape'), ('animal', 'Animal'), ('number', 'Number')], default='color', help_text='Type of lesson (color, shape, etc.)', max_length=20),
        ),
    ]
