# Generated by Django 5.0.6 on 2025-08-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0028_story_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='story_type',
            field=models.CharField(choices=[('color', 'Color'), ('shape', 'Shape'), ('animal', 'Animal'), ('number', 'Number')], default='color', help_text='Type of story (color, shape, etc.)', max_length=20),
        ),
    ]
