# Generated by Django 5.0.6 on 2025-08-30 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0029_story_story_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='story_type',
        ),
    ]
