# Generated by Django 5.0.6 on 2025-09-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0036_alter_lesson_lesson_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='order',
            field=models.IntegerField(default=0, help_text='Order for displaying courses (lower comes first)'),
        ),
    ]
