# Generated by Django 5.0.6 on 2025-09-03 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0037_course_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title or heading for the video', max_length=100)),
                ('video_url', models.URLField(help_text='YouTube or video embed URL for the video')),
                ('order', models.IntegerField(default=0, help_text='Order for displaying videos')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='kids.lesson')),
            ],
        ),
    ]
