# Generated by Django 5.0.6 on 2025-09-06 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0042_spaceshooterhighscore'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaceshooterhighscore',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='space_shooter_highscores', to=settings.AUTH_USER_MODEL),
        ),
    ]
