# Generated by Django 5.0.6 on 2025-09-15 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0043_alter_spaceshooterhighscore_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpaceShooterHighScore',
        ),
    ]
